//! Polynomial representations used by the sumcheck protocol.
//!
//! Variable-order convention (frozen with S-2): a multilinear polynomial
//! in `n` variables is stored as its evaluation table over {0,1}^n, where
//! variable `x_0` is the MOST significant index bit and binding proceeds
//! x_0, x_1, ... This convention must match the Isabelle model's variable
//! enumeration when R2 is discharged.

use ssgkr_primitives::field::Field;

#[cfg(creusot)]
use core::ops::{Add, Mul, Sub};
#[cfg(creusot)]
use creusot_std::prelude::{
    Int, Seq, ensures, extern_spec, inv, invariant, logic, pearlite, requires, snapshot, trusted,
};

/// Foreign-constant type-invariant bridge axiom (R2 independent audit,
/// supervisor-approved introduction): a well-typed foreign constant
/// satisfies its (opaque) type invariant.
///
/// ZERO VALUE CONTENT: the only claim is `inv(F::ZERO)` - no arithmetic
/// or value fact. For a foreign field element `inv` is an opaque
/// predicate that Creusot already ASSUMES for every function argument
/// and return value (the "generated by Creusot" requires/ensures,
/// creusot-std invariant.rs); for associated CONSTANTS the toolchain
/// emits the same axiom guarded by `false` (coma:
/// `axiom const_ZERO_spec: false -> inv_F const_ZERO`), so constants
/// fall outside the assumption - a tool artifact (the R1 wall-4 layer-3
/// foreign-constant gap), not a semantic gap. This axiom asserts for
/// the constant exactly what the tool assumes for values, and is the
/// design B.6 black-box class ("p3-field correctness", well-formedness
/// face). Upstream candidate: a native foreign-const invariant
/// mechanism (refinement_status section 13).
///
/// ACTIVATION: an axiom module is only imported where referenced, so
/// each consuming loop names this symbol in an `invariant(...)` clause
/// (prove / eval_at). REVERT PATH: delete this item and those loop
/// invariants; the two goals return to honest holes (27/28, 13/15).
#[cfg(creusot)]
#[trusted]
#[logic(opaque)]
#[ensures(result)]
#[ensures(inv(F::ZERO))]
pub fn foreign_zero_wf<F: Field>() -> bool {
    dead
}

// `Vec::truncate` has no creusot-std contract yet; supply the std fact
// (length clamp + prefix preservation), body untouched. Same class as the
// R1 `div_ceil`/`Result::map` extern specs.
#[cfg(creusot)]
extern_spec! {
    impl<T, A: std::alloc::Allocator> Vec<T, A> {
        #[ensures((^self)@.len() == if len@ <= self@.len() { len@ } else { self@.len() })]
        #[ensures(forall<i: Int> 0 <= i && i < (^self)@.len() ==> (^self)@[i] == self@[i])]
        fn truncate(&mut self, len: usize);
    }
}

// Claim-free permissibility specs for the arithmetic operator traits:
// field element arithmetic dispatches through these, and the plonky3
// impls carry no Creusot contracts, so without a spec every `+`/`-`/`*`
// call site carries an impossible precondition (R1 trap 4). The explicit
// `requires(true)` pins the otherwise-abstract trait precondition to
// "always callable"; no ensures = zero claims about the values (the
// black-box boundary of design B.6, "p3-field operation correctness").
// Same class as the R1 claim-free `from_u32` spec. Primitive integers
// are unaffected (rustc lowers their arithmetic to built-in MIR ops).
#[cfg(creusot)]
extern_spec! {
    mod core {
        mod ops {
            trait Add<Rhs> {
                #[requires(true)]
                fn add(self, rhs: Rhs) -> Self::Output;
            }
            trait Sub<Rhs> {
                #[requires(true)]
                fn sub(self, rhs: Rhs) -> Self::Output;
            }
            trait Mul<Rhs> {
                #[requires(true)]
                fn mul(self, rhs: Rhs) -> Self::Output;
            }
        }
    }
}

// `Vec::is_empty` std fact (creusot-std gap; the R1 primitives crate
// supplied the slice `is_empty` the same way; `Vec::clone` already has
// a creusot-std contract).
#[cfg(creusot)]
extern_spec! {
    impl<T, A: std::alloc::Allocator> Vec<T, A> {
        #[ensures(result == (self@.len() == 0))]
        fn is_empty(&self) -> bool;
    }
}

/// Dense multilinear polynomial as an evaluation table of length 2^n.
///
/// AFP refinement map (`multi_variate_polynomial`):
///   `vars` ~ implicit set {0..n} via `num_vars`,
///   `eval` ~ [`Self::evaluate`],
///   `inst` ~ [`Self::fix_first_var`] (partial substitution, one variable).
///
/// `PartialEq`/`Eq` are gated out of the Creusot build: under Creusot a
/// derived `PartialEq` demands `DeepModel` on every field type, and the
/// generic `F` cannot carry one (foreign field elements, orphan rule) -
/// same seam as `Digest<F>` in the primitives crate (R1).
#[derive(Clone, Debug)]
#[cfg_attr(not(creusot), derive(PartialEq, Eq))]
pub struct MultilinearPoly<F> {
    evals: Vec<F>,
    num_vars: usize,
}

/// R2 logic projections (opaque seam, trap-13): every private-field
/// mention stays inside this module; consumers (the protocol crate's
/// layer reduction) see only these symbols plus the contract equations.
#[cfg(creusot)]
impl<F> MultilinearPoly<F> {
    /// `num_vars`, as Int.
    #[logic]
    pub fn n_vars(self) -> Int {
        pearlite! { self.num_vars@ }
    }
    /// The evaluation table, as a logical sequence.
    #[logic]
    pub fn table(self) -> Seq<F> {
        pearlite! { self.evals@ }
    }
}

impl<F: Field> MultilinearPoly<F> {
    /// Build from an evaluation table; length must be a power of two.
    ///
    /// R2 contract (Isabelle: the table of an `mle n f` instance has
    /// length `2 ^ n`). Machine-checked slice: the table is preserved
    /// verbatim and non-empty on success. The arithmetic link
    /// `table.len() == 2^n_vars` is EXPRESSION-WALLED: the code computes
    /// `n` via `trailing_zeros`, whose creusot-std spec is an opaque
    /// shift/mask fact, and the default integer prelude declares the
    /// bitwise ops without axioms (upstream not_planned, R1 wall 3) - so
    /// the bit-level fact cannot be connected to `Int::pow2` in the
    /// int-mode logic. Stated here as documentation, held by the model
    /// side (`Multilinear_Extension.mle` is indexed by `2 ^ n` by
    /// construction).
    #[cfg_attr(creusot, ensures(match result {
        Ok(p) => p.table() == evals@ && p.table().len() > 0,
        Err(_) => true,
    }))]
    pub fn from_evals(evals: Vec<F>) -> Result<Self, PolyError> {
        if evals.is_empty() || !evals.len().is_power_of_two() {
            return Err(PolyError::NotPowerOfTwo { len: evals.len() });
        }
        let num_vars = evals.len().trailing_zeros() as usize;
        Ok(Self { evals, num_vars })
    }

    /// Number of variables `n`.
    #[cfg_attr(creusot, ensures(result@ == self.n_vars()))]
    pub fn num_vars(&self) -> usize {
        self.num_vars
    }

    /// Evaluation table access (length 2^n).
    #[cfg_attr(creusot, ensures(result@ == self.table()))]
    pub fn evals(&self) -> &[F] {
        &self.evals
    }

    /// Evaluate at an arbitrary point (spec-literal Lagrange fold,
    /// O(2^n) memory walk; 2a may optimize but MUST preserve semantics).
    ///
    /// R2 contract: the arity and table-domain `requires` are active
    /// (machine-checked; a requires imposes an obligation on callers, so
    /// it sits outside the ensures/invariant wall). The table-domain
    /// clause `table.len() == 2^n_vars` is exactly the domain of the
    /// model's `mle n` (a table indexed by `{0..<2^n}`); values built by
    /// [`Self::from_evals`] satisfy it by construction. The VALUE clause
    /// (`result == Multilinear_Extension.mle n table point`) is
    /// EXPRESSION-WALLED: field arithmetic goes through the plonky3
    /// operator impls, which carry no Creusot contracts (design B.6
    /// black box: "p3-field operation correctness"), so there is no
    /// logic-level `+`/`*` to state the fold against. Held by the model.
    #[cfg_attr(creusot, requires(point@.len() == self.n_vars()))]
    #[cfg_attr(creusot, requires(self.table().len() == self.n_vars().pow2()))]
    #[cfg_attr(creusot, requires(self.n_vars() >= 0))]
    pub fn evaluate(&self, point: &[F]) -> F {
        assert_eq!(point.len(), self.num_vars, "point arity mismatch");
        let mut table = self.evals.clone();
        #[cfg_attr(creusot, invariant(
            table@.len() == (self.n_vars() - produced.len()).pow2()
        ))]
        for &r in point {
            let half = table.len() / 2;
            #[cfg_attr(creusot, invariant(table@.len() == 2 * half@))]
            for i in 0..half {
                // x_0 is the MSB: fold the top bit first.
                table[i] = table[i] + r * (table[i + half] - table[i]);
            }
            table.truncate(half);
        }
        table[0]
    }

    /// Bind the first (most significant) variable to `r`, reducing arity
    /// by one. This is the Rust counterpart of AFP `inst` restricted to a
    /// single variable, which is exactly how sumcheck consumes it.
    ///
    /// R2 contract (Isabelle/AFP: one `inst` step removes one variable
    /// and halves the table): arity decrement and table halving are
    /// machine-checked; the VALUE clause (the folded entries interpolate
    /// the two halves) is expression-walled like [`Self::evaluate`].
    #[cfg_attr(creusot, requires((*self).n_vars() > 0))]
    #[cfg_attr(creusot, ensures((^self).n_vars() == (*self).n_vars() - 1))]
    #[cfg_attr(creusot, ensures((^self).table().len() == (*self).table().len() / 2))]
    pub fn fix_first_var(&mut self, r: F) {
        assert!(self.num_vars > 0, "no variable left to bind");
        let half = self.evals.len() / 2;
        #[cfg_attr(creusot, invariant(
            self.evals@.len() == 2 * half@ || self.evals@.len() == 2 * half@ + 1
        ))]
        for i in 0..half {
            self.evals[i] = self.evals[i] + r * (self.evals[i + half] - self.evals[i]);
        }
        self.evals.truncate(half);
        self.num_vars -= 1;
    }
}

/// Univariate round polynomial `g_j`, coefficients in ascending order
/// (c_0 + c_1 x + c_2 x^2 + ...). Degree is bounded by the instance's
/// `degree_bound`; the verifier enforces the bound (AFP deg check).
///
/// `PartialEq`/`Eq` gated out of the Creusot build (generic `F` cannot
/// carry `DeepModel` - see [`MultilinearPoly`]).
#[derive(Clone, Debug)]
#[cfg_attr(not(creusot), derive(PartialEq, Eq))]
pub struct RoundPoly<F> {
    coeffs: Vec<F>,
}

/// R2 logic projection (opaque seam, trap-13) - see [`MultilinearPoly`].
#[cfg(creusot)]
impl<F> RoundPoly<F> {
    /// The ascending coefficient vector, as a logical sequence.
    #[logic]
    pub fn cs(self) -> Seq<F> {
        pearlite! { self.coeffs@ }
    }
}

impl<F: Field> RoundPoly<F> {
    /// Construct from ascending coefficients (empty = zero polynomial).
    #[cfg_attr(creusot, ensures(result.cs() == coeffs@))]
    pub fn from_coeffs(coeffs: Vec<F>) -> Self {
        Self { coeffs }
    }

    /// Ascending coefficient slice.
    #[cfg_attr(creusot, ensures(result@ == self.cs()))]
    pub fn coeffs(&self) -> &[F] {
        &self.coeffs
    }

    /// Degree (0 for the zero/constant polynomial).
    ///
    /// R2 contract: this is the quantity the verifier bounds per round
    /// (AFP `deg` check, reduce.rs `LAYER_ROUND_DEGREE`).
    #[cfg_attr(creusot, ensures(result@ ==
        if self.cs().len() == 0 { 0 } else { self.cs().len() - 1 }))]
    pub fn degree(&self) -> usize {
        self.coeffs.len().saturating_sub(1)
    }

    /// Horner evaluation.
    ///
    /// R2 audit update: the former residual goals (`inv(acc)` / the
    /// first `*` precondition, rooted in `acc` starting at `F::ZERO`)
    /// are discharged by the [`foreign_zero_wf`] bridge axiom plus the
    /// `inv(acc)` loop invariant - the body is now fully machine-checked
    /// (safety and invariant goals; no value contract). The value
    /// semantics (Horner = polynomial evaluation) stays
    /// expression-walled (black-box field ops, design B.6).
    pub fn eval_at(&self, x: F) -> F {
        let mut acc = F::ZERO;
        #[cfg_attr(creusot, invariant(foreign_zero_wf::<F>()))]
        #[cfg_attr(creusot, invariant(inv(acc)))]
        for &c in self.coeffs.iter().rev() {
            acc = acc * x + c;
        }
        acc
    }
}

/// Errors from polynomial construction.
///
/// `PartialEq`/`Eq` gated out of the Creusot build: no contract consumes
/// error equality (test-only comparisons), and the derived-eq refinement
/// obligation fails against the derived `DeepModel` in this toolchain
/// rev, so the equality surface is simply not translated.
#[derive(Clone, Debug)]
#[cfg_attr(not(creusot), derive(PartialEq, Eq))]
pub enum PolyError {
    /// Evaluation table length is not a power of two.
    NotPowerOfTwo {
        /// Offending length.
        len: usize,
    },
}
