#!/usr/bin/env python3
"""Regression fixtures for portable candidate Git-mode resolution."""

from __future__ import annotations

import importlib.util
from pathlib import Path
import sys


def load_verifier():
    sys.dont_write_bytecode = True
    path = Path(__file__).with_name("verify.py")
    spec = importlib.util.spec_from_file_location("statesync_gkr_release_verify", path)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load release verifier")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> int:
    verifier = load_verifier()

    # DrvFS-like execute bits on ordinary untracked files must not become an
    # intended Git executable mode in the canonical Windows worktree.
    assert verifier.resolve_candidate_mode(None, True, 0o755) == "100644"
    assert verifier.resolve_candidate_mode(None, True, 0o777) == "100644"

    # A tracked executable remains executable even if the current filesystem
    # projection is less permissive.
    assert verifier.resolve_candidate_mode("100755", True, 0o644) == "100755"

    # A source archive has no Git index, so its actual POSIX mode is authority.
    assert verifier.resolve_candidate_mode(None, False, 0o755) == "100755"
    assert verifier.resolve_candidate_mode(None, False, 0o644) == "100644"

    # One exact scholar name in the paper bibliography overlaps the AI-tool
    # scanner. The exception must not suppress any other occurrence.
    tool_name = "Clau" + "de"
    scholar = "March{\\'e}, " + tool_name
    bibliography = verifier.PAPER_BIBLIOGRAPHY_PATH
    assert tool_name not in verifier.ai_attribution_scan_text(
        bibliography, f"author = {{{scholar}}}"
    )
    assert tool_name in verifier.ai_attribution_scan_text(
        bibliography, f"note = {{Generated by {tool_name}}}"
    )
    assert tool_name in verifier.ai_attribution_scan_text(
        "README.md", f"author = {{{scholar}}}"
    )

    print("mode-policy-fixtures=PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
